### ISSUE TITLE
Support for module version checking

### ISSUE THREAD

**Issue by awdhaan** [martensnico/Office365.Connect#9]
Attended your session on SPSNL2018. Enjoyed it!
Based on what I saw, it might be cool to do a version check of all the installed modules as these change so often causing some FOMO in capabilities.

Happy to work on this together.

~Andries

**Comment by martensnico** [comment]
Thanks for attending. Great addition. I will have to do some checks to see how this can be accomplished, especially with the "modules" that require a .exe download like the SharePoint Online Management Shell. (This one failed in the demo because Microsoft released a new version and removed the old one).

**Comment by martensnico** [comment]
Going to add this: https://gist.github.com/jdhitsolutions/8a49a59c5dd19da9dde6051b3e58d2d0.

**Comment by martensnico** [comment]
Added the functionality!
